<a href="https://colab.research.google.com/github/RAED963F/artificial_Intelligence_engineering-51/blob/main/S01_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# # Домашнее задание 01 - Основы NumPy
# **Студент:** Раед
# **Группа:** Искусственный интеллект - 51
# **Дата:** 2024

# 1. Импорт библиотеки NumPy
import numpy as np
print("✅ NumPy успешно импортирован")


# 2. Создание различных массивов
print("=" * 50)
print("2. Создание массивов:")

# Массив из списка
arr1 = np.array([10, 20, 30, 40, 50])
print(f"Массив чисел: {arr1}")

# Массив нулей
arr2 = np.zeros((3, 3))
print(f"\nМассив нулей 3x3:\n{arr2}")

# Массив единиц
arr3 = np.ones((2, 4))
print(f"\nМассив единиц 2x4:\n{arr3}")

# Массив с диапазоном
arr4 = np.arange(0, 20, 4)  # от 0 до 20 с шагом 4
print(f"\nМассив с диапазоном: {arr4}")

# 3. Свойства массивов
print("=" * 50)
print("3. Свойства массива arr2:")

print(f"Форма (shape): {arr2.shape}")
print(f"Тип данных (dtype): {arr2.dtype}")
print(f"Количество измерений (ndim): {arr2.ndim}")
print(f"Количество элементов (size): {arr2.size}")

# 4. Индексация и срезы
print("=" * 50)
print("4. Индексация и срезы:")

# Пример массива
arr5 = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(f"Массив: {arr5}")

print(f"\n- Первый элемент: {arr5[0]}")
print(f"- Третий элемент: {arr5[2]}")
print(f"- Последний элемент: {arr5[-1]}")
print(f"- Элементы с 2 по 5: {arr5[2:5]}")
print(f"- Каждый второй элемент: {arr5[::2]}")

# Пример двумерного массива
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nДвумерный массив:\n{matrix}")
print(f"\n- Вторая строка: {matrix[1]}")
print(f"- Первый столбец: {matrix[:, 0]}")
print(f"- Элемент в строке 1, столбце 2: {matrix[1, 2]}")

# 5. Математические операции и статистика
print("=" * 50)
print("5. Математические операции:")

# Создаем два массива
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])

print(f"Массив a: {a}")
print(f"Массив b: {b}")

# Операции
print(f"\n- Сложение: {a + b}")
print(f"- Вычитание: {b - a}")
print(f"- Умножение (поэлементно): {a * b}")
print(f"- Деление: {b / a}")

# Статистика
print(f"\nСтатистика массива a:")
print(f"  • Среднее значение: {np.mean(a):.2f}")
print(f"  • Сумма: {np.sum(a)}")
print(f"  • Максимальное значение: {np.max(a)}")
print(f"  • Минимальное значение: {np.min(a)}")
print(f"  • Стандартное отклонение: {np.std(a):.2f}")


# 6. Дополнительные примеры (необязательно)
print("=" * 50)
print("6. Дополнительные примеры:")

# Случайная матрица
random_matrix = np.random.randint(1, 100, size=(3, 3))
print(f"Случайная матрица 3x3:\n{random_matrix}")

# Изменение формы
arr_flat = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr_flat.reshape(2, 3)
print(f"\nПлоский массив: {arr_flat}")
print(f"После изменения формы на 2x3:\n{arr_reshaped}")

print("\n" + "=" * 50)
print("✅ Все требования домашнего задания выполнены успешно!")

✅ NumPy успешно импортирован
2. Создание массивов:
Массив чисел: [10 20 30 40 50]

Массив нулей 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Массив единиц 2x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Массив с диапазоном: [ 0  4  8 12 16]
3. Свойства массива arr2:
Форма (shape): (3, 3)
Тип данных (dtype): float64
Количество измерений (ndim): 2
Количество элементов (size): 9
4. Индексация и срезы:
Массив: [ 5 10 15 20 25 30 35 40]

- Первый элемент: 5
- Третий элемент: 15
- Последний элемент: 40
- Элементы с 2 по 5: [15 20 25]
- Каждый второй элемент: [ 5 15 25 35]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

- Вторая строка: [4 5 6]
- Первый столбец: [1 4 7]
- Элемент в строке 1, столбце 2: 6
5. Математические операции:
Массив a: [1 2 3 4 5]
Массив b: [ 2  4  6  8 10]

- Сложение: [ 3  6  9 12 15]
- Вычитание: [1 2 3 4 5]
- Умножение (поэлементно): [ 2  8 18 32 50]
- Деление: [2. 2. 2. 2. 2.]

Статистика массива a:
  • Среднее значение: 3.00
  • Сумма: 15
  • Максимальное значение: 5
  • Миним